//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiApp5.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiApp5.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi naslov projekta.
        /// </summary>
        internal static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi ime radnika.
        /// </summary>
        internal static string AddWorker {
            get {
                return ResourceManager.GetString("AddWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovaj datum je već upisan.
        /// </summary>
        internal static string DateReserved {
            get {
                return ResourceManager.GetString("DateReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbaci.
        /// </summary>
        internal static string DialogCancel {
            get {
                return ResourceManager.GetString("DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        internal static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogOK {
            get {
                return ResourceManager.GetString("DialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        internal static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni projekat {0}?.
        /// </summary>
        internal static string RemoveProject {
            get {
                return ResourceManager.GetString("RemoveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve informacije vezane za ovaj projekat biće trajno uklonjene.
        /// </summary>
        internal static string RemoveProjectDescription {
            get {
                return ResourceManager.GetString("RemoveProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni izveštaj {0}?.
        /// </summary>
        internal static string RemoveReport {
            get {
                return ResourceManager.GetString("RemoveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve informacije vezane za ovaj izveštaj radnika {0} biće trajno uklonjene.
        /// </summary>
        internal static string RemoveReportDescription {
            get {
                return ResourceManager.GetString("RemoveReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni radnika {0}?.
        /// </summary>
        internal static string RemoveWorker {
            get {
                return ResourceManager.GetString("RemoveWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve informacije vezane za ovog radnika na projektu {0} biće trajno uklonjene.
        /// </summary>
        internal static string RemoveWorkerDescription {
            get {
                return ResourceManager.GetString("RemoveWorkerDescription", resourceCulture);
            }
        }
    }
}
